# Generated by Django 6.0.3 on 2026-03-07 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.CharField(max_length=200)),
                ('date_added1', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
