# Generated by Django 6.0.3 on 2026-03-07 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_topic2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic2',
        ),
    ]
