# Generated by Django 6.0.3 on 2026-03-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0004_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
    ]
